# Generated by Django 5.1.5 on 2025-02-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_commentlike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='author',
            new_name='user',
        ),
    ]
